run-name: "Raindex Metrics: ${{ github.event.inputs.network }} - ${{ github.event.inputs.token }} - ${{ github.event.inputs.duration }}"
on:
  workflow_dispatch:
    inputs:
      network:
        description: 'Network'
        required: true
        type: choice
        options:
          - mainnet
          - polygon
          - bsc
          - base
          - flare
          - arbitrum

      token:
        description: 'TOKEN'
        required: true
        type: choice
        options:
          - PAI
          - LOCK
          - IOEN
          - MNW
          - TFT
          - WLTH
          - PAID
          - LUCKY
          - WPOL
          - QUICK_OLD
          - QUICK_NEW
          - WFLR
          - sFLR
          - cysFLR
          - KIMA
      
      duration:
        description: 'Duration for metrics'
        required: true
        type: choice
        options:
          - daily
          - weekly
          - monthly

jobs:
  metrics:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      # https://github.com/actions/runner-images/issues/2840#issuecomment-2272410832
      - run: |
          sudo rm -rf \
            "$AGENT_TOOLSDIRECTORY" \
            /opt/google/chrome \
            /opt/microsoft/msedge \
            /opt/microsoft/powershell \
            /opt/pipx \
            /usr/lib/mono \
            /usr/local/julia* \
            /usr/local/lib/android \
            /usr/local/lib/node_modules \
            /usr/local/share/chromium \
            /usr/local/share/powershell \
            /usr/share/dotnet \
            /usr/share/swift
          df -h

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v4
      - uses: DeterminateSystems/magic-nix-cache-action@v2

      - name: Install and Build Dependencies
        run: nix develop -c build-js-bindings

      - name: Raindex Metrics
        env:
          TOKEN_SYMBOL: ${{ inputs.token }}
          NETWORK: ${{ inputs.network }}
          DURATION: ${{ inputs.duration }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          RUN_DATETIME=$(date -u '+%Y-%m-%d-%H-%M-%S-UTC')
          echo "RUN_DATETIME=$(date -u '+%Y-%m-%d-%H-%M-%S-UTC')" >> $GITHUB_ENV
          echo "NETWORK=$NETWORK"
          echo "TOKEN_SYMBOL=$TOKEN_SYMBOL"
          echo "DURATION=$DURATION"
          echo "RUN_DATETIME=$RUN_DATETIME"
          nix develop -c raindex-metrics > ./$NETWORK-$TOKEN_SYMBOL-$DURATION-$RUN_DATETIME.md

      - name: Upload markdown file
        uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.network }}-${{ inputs.token }}-${{ inputs.duration }}-${{ env.RUN_DATETIME }}.md
          path: ${{ inputs.network }}-${{ inputs.token }}-${{ inputs.duration }}-${{ env.RUN_DATETIME }}.md

