name: Raindex Metrics
on:
  workflow_dispatch:
    inputs:
      network:
        description: 'Network'
        required: true
        type: choice
        options:
          - mainnet
          - polygon
          - bsc
          - base
          - flare

      token:
        description: 'TOKEN'
        required: true
        type: choice
        options:
          - PAI
          - LOCK
          - IOEN
          - TFT
          - WLTH
          - PAID
          - LUCKY
          - WPOL
          - QUICK_OLD
          - QUICK_NEW
          - WFLR
          - sFLR

jobs:
  metrics:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      # https://github.com/actions/runner-images/issues/2840#issuecomment-2272410832
      - run: |
          sudo rm -rf \
            "$AGENT_TOOLSDIRECTORY" \
            /opt/google/chrome \
            /opt/microsoft/msedge \
            /opt/microsoft/powershell \
            /opt/pipx \
            /usr/lib/mono \
            /usr/local/julia* \
            /usr/local/lib/android \
            /usr/local/lib/node_modules \
            /usr/local/share/chromium \
            /usr/local/share/powershell \
            /usr/share/dotnet \
            /usr/share/swift
          df -h

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v4
      - uses: DeterminateSystems/magic-nix-cache-action@v2

      - name: Install and Build Dependencies
        run: nix develop -c build-js-bindings

      - name: Raindex Metrics
        env:
          TOKEN_SYMBOL: ${{ inputs.token }}
          NETWORK: ${{ inputs.network }}
        run: nix develop -c raindex-metrics
