name: Raindex Metrics
on:
  workflow_dispatch:
    inputs:
      network:
        description: 'Network'
        required: true
        type: choice
        options:
          - polygon
          - bsc

      token:
        description: 'TOKEN'
        required: true
        type: choice
        options:
          - IOEN
          - TFT

jobs:
  generate_and_post_report:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v4
      - uses: DeterminateSystems/magic-nix-cache-action@v2

      - name: Install and Build Dependencies
        run: nix develop -c build-js-bindings

      - name: Raindex Metrics
        env:
          TOKEN_SYMBOL: ${{ inputs.token }}
          NETWORK: ${{ inputs.network }}
        run: nix develop -c raindex-metrics
